lib/simulator-xcode-6.js, package.json
Allow user to `updateLocationSettings()` on a simulator.
=> Expose sim.updateLocationSettings

index.js, lib/utils.js
Not sure it is the best way, but we need it.
=> Exposing killAllSimulators

lib/settings.js, lib/simulator-xcode-6.js
Some issues came up in the Safari flow.
=> Fix some async issues with safari handling

index.js, lib/simulator-xcode-6.js, lib/utils.js
This is needed to fully support ios 9 in 1.5
=> Add method to end all sim daemons

lib/simulator-xcode-6.js, lib/utils.js, package.json, test/simulator-e2e-specs.js, test/unit/settings-specs.js, test/unit/simulator-common-specs.js, test/unit/simulator-specs.js, test/unit/utils-specs.js
Reference https://github.com/appium/appium-instruments/pull/42
=> Fix kill sims for xcode 7

lib/simulator-xcode-6.js, package.json, test/simulator-e2e-specs.js
=> cleanup work for appium 1.5

lib/simulator-xcode-6.js
=> Explicitly parse int as base 10

lib/simulator-xcode-6.js, lib/simulator-xcode-7.js, lib/tail-until.js, package.json, test/simulator-e2e-specs.js, test/unit/tail-until-specs.js
=> detect simulator start time using system log

README.md, lib/simulator-xcode-6.js, package.json, test/simulator-e2e-specs.js, test/unit/simulator-common-specs.js
=> Clean custom app

lib/extensions/index.js, lib/extensions/prepare-apps.js, lib/simulator-xcode-6.js, lib/tail-until.js, lib/utils.js, package.json, test/simulator-e2e-specs.js
- add support for moving built in apps
- fix tests
- kill the tail process correctly
=> Add support for moving built in app

lib/simulator-xcode-6.js
Clean up retry (using `asyncbox`s `retryInterval` instead of `for` loop). Also try moving an `await` to try to fix a weird bug. :(
@Jonahss
=> Fix retry logic

lib/extensions/prepare-apps.js, lib/settings.js, lib/simulator-xcode-7.js
Allow `iPhone 6 Plus`, `iPhone 6s`, and `iPhone 6s Plus`.
=> Add new iOS devices

README.md, lib/simulator-xcode-6.js, lib/simulator-xcode-7.js, package.json, test/simulator-e2e-specs.js
Depends on https://github.com/appium/node-simctl/pull/15
@imurchie for review?
=> add isRunning() and openUrl(url)

lib/extensions/index.js, lib/extensions/isolate-sim.js, test/simulator-e2e-specs.js, test/unit/isolate-sim-specs.js
=> fix isolateSim and add tests

lib/simulator-xcode-6.js
=> throw an error, not a string

lib/utils.js, test/simulator-e2e-specs.js, test/unit/utils-specs.js
Addresses https://github.com/appium/appium/issues/6174
=> Catch application not running error

lib/simulator-xcode-6.js, test/simulator-e2e-specs.js
Add a method to remove an application from the simulator.
=> Add removeApp method

lib/simulator-xcode-7.3.js
Address #54 
The paths are now the same for all Xcode 7s.
=> No longer need special code for 7.3

.travis.yml, lib/simulator-xcode-6.js, lib/simulator-xcode-7.3.js, package.json, test/simulator-e2e-specs.js
=> Fix small typo

.travis.yml, lib/utils.js, test/simulator-e2e-specs.js
Attempting to provide more information for cases like https://github.com/appium/appium/issues/6452
=> Make sim check more explicit

lib/simulator-xcode-6.js, lib/simulator.js, test/unit/simulator-specs.js
Just allow it through, and return the same driver as for 7.3. If anything comes up as different, we can fix it.
=> Adds preliminary support for Xcode 8

.eslintrc, .travis.yml, LICENSE, lib/simulator-xcode-6.js, package.json, test/assets/deviceList.js, test/simulator-e2e-specs.js, test/unit/settings-specs.js, test/unit/simulator-common-specs.js, test/unit/utils-specs.js
Add eslint, and fix any problems that it found.
=> Add eslint and precommit checks

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/tail-until.js, test/simulator-e2e-specs.js
In iOS 10 the files have changed a little bit, for testing whether the sim is fully prepared.
=> Remove file that is often not there

lib/simulator-xcode-6.js
We ought to be able to pass a timeout to the run command.
=> Make run timeout configurable

lib/simulator-xcode-8.js
There is still nothing better. :(
=> Add boot indicator for ios 10.1

.travis.yml, test/simulator-e2e-specs.js
Extend testing to supported node versions, and ios 10 and 9.3.
=> Update travis config

README.md, lib/simulator-xcode-6.js
These changes are based on https://github.com/appium/appium/issues/6925
=> Make it possible to adjust simulator scale factor

lib/simulator-xcode-8.js
Because we can do it (and get a t-shirt  :-P )
=> Speed up Safari startup

index.js, lib/simulator-xcode-6.js, lib/simulator-xcode-8.js
=> Export the BOOT_COMPLETED_EVENT, so it can be used in other modules

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, package.json, test/simulator-e2e-specs.js
We've let some logic seep out. Reign it back in.
See, for instance, https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L710
=> Add isAppInstalled method

lib/simulator-xcode-6.js
People would like to have this option configurable
=> Make the connect hardware keyboard option configurable

lib/utils.js, test/unit/utils-specs.js
This PR addresses complicated simulator cases when it cannot be terminated easily, for example https://github.com/appium/appium/issues/7904
=> Tune simulator shutdown procedure

lib/simulator-xcode-6.js
=> Update the list of Safari folders for browser cleanup 

lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, lib/simulator.js, test/unit/simulator-specs.js
Just allow things to start. Any updates that are necessary will come as testing proceeds.
=> First steps in supporting Xcode9/iOS 11

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, test/simulator-e2e-specs.js
Did refactoring of Simulator run options as per @jlipps's comment for https://github.com/appium/appium-ios-simulator/pull/112
Please do not merge this PR until the other PR which contains the necessary changes in xcuitest driver is done.
=> Refactor setting of Simulator run options

.travis.yml, lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, lib/utils.js
And a few little changes to make it work consistently and reliably.
=> Test with Xcode 9/iOS 11 in Travis

lib/simulator-xcode-8.js, test/simulator-e2e-specs.js
That's unexpected, but it works
=> Add functional test for parallel simulators startup

test/simulator-e2e-specs.js
check headless mode functionality on Xcode9+
=> Add a separate test for headless mode

lib/simulator-xcode-8.js, package.json
The PR fixes system applications detection on Simulator. Please do not merge it until https://github.com/appium/node-simctl/commit/a5c4bfb33fcaf5139cbfeccc62c3dc49d005f06c is published
=> Fix system apps detection

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js
Kudos to @vrunoa for sharing the information about such nice feature.
=> Add a possibility to change default Simulator preferences

lib/simulator-xcode-9.js
Apple has just renamed the corresponding menu item there
=> Fix Simulator enrolment for Xcode9 SDK

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js
Also did some refactoring to improve the algorithm for multi-window configuration.
=> Add a possibility to perform Shake gesture and set custom geolocation coordinates via AppleScript

lib/simulator-xcode-9.js
Addresses https://github.com/appium/appium/issues/9792
=> Do not raise an error if preferences plist update fails

lib/simulator-xcode-6.js, test/functional/simulator-e2e-specs.js
Now it will be possible to backup and selectively restore keychains during full reset
=> Add methods for keychains backup and restore

package.json, test/unit/calendar-specs.js, test/unit/certificate-specs.js, test/unit/isolate-sim-specs.js, test/unit/settings-specs.js, test/unit/simulator-common-specs.js, test/unit/simulator-specs.js, test/unit/tail-until-specs.js, test/unit/utils-specs.js
https://github.com/appium/appium/issues/10016
=> Update deps and lint

lib/simulator-xcode-9.js
Thanks to @vrunoa for the investigation.
=> Put ConnectHardwareKeyboard into local simulator preferences

lib/certificate.js
Part of https://github.com/appium/appium/issues/10685
=> Fix buffer usage

lib/calendar.js, lib/utils.js
The query is all over the place, but we just need it to be filled with `0`s.  So query the number of columns and fill that number in.
=> Dynamically figure out column count for calendar query

.travis.yml, lib/simulator-xcode-6.js
New sims on Xcode 10 take a while.
Also add Xcode 10 to the Travis build.
=> Increase retries for Xcode 10 sim starting

lib/settings.js, lib/simulator-xcode-6.js
We had two lines in the logs for every check.
=> Clean up logging for isFresh

lib/fbsimctl-utils.js, lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, lib/utils.js, test/functional/simulator-e2e-specs.js
This PR includes:
- setting geolocation with fbsimctl (fallback to AppleScript)
- focus Simulator window with fbsimctl (fallback to AppleScript)
- clear keychains while simulator is running
=> Incorporate some fbsimctl features

lib/calendar.js, lib/certificate.js, lib/permissions.js, lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/tcc-db.js, lib/utils.js, test/functional/simulator-e2e-specs.js, test/unit/calendar-specs.js
Also refactored existing classes that rely on TCC database
=> Add possibility to set permissions per bundle id

NOTICE.txt, lib/fbsimctl-utils.js, lib/permissions.js, lib/simulator-xcode-6.js, package.json, test/functional/simulator-e2e-specs.js
SQLite TCC.db update is tricky. Lets rely on third party for doing hacks %)
=> Use WIX in order to set permissions

package.json
Greenkeeper is broken. I've contacted support and am waiting for solutions.
=> Update node-simctl to 4.0.0

lib/simulator-xcode-6.js, lib/utils.js, test/unit/utils-specs.js
See https://github.com/appium/appium-ios-simulator/pull/169#discussion_r251698269 for more details
=> Speed up simulator pid detection

.travis.yml, test/functional/helpers.js, test/functional/simulator-e2e-specs.js
Some refactoring, and an extended timeout (for the case where we launch multiple parallel sims, which Travis has a hard time with).
=> Work on the build

lib/simulator-xcode-8.js, lib/simulator-xcode-9.js
Addresses https://github.com/appium/appium/issues/12765
=> Update headless logic

lib/simulator-xcode-9.js
Addresses https://github.com/appium/appium/issues/13010
=> Remove the dash character from Simulator window  name

lib/settings.js, lib/simulator-xcode-11.js, lib/simulator-xcode-6.js
Quite simple to set the dark mode ui preferences, and they can be done _before_ the sim is started!
Cc @wswebcreation
=> feat: add function to set dark mode in sim

.travis.yml
Update `brew` so install doesn't fail, as it has been recently.
=> chore: fix the build

lib/simulator-xcode-10.js, lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/utils.js, test/functional/simulator-e2e-specs.js
Got an idea from https://apple.stackexchange.com/questions/352107/getting-list-of-running-processes-on-ios-simulator
=> feat: Add a method to list running processes

lib/settings.js, lib/simulator-xcode-11.4.js, lib/simulator-xcode-11.js, lib/simulator-xcode-6.js, lib/simulator.js
The new features are:
- UI appearance setting/retrieval
- Apps permissions management
- Keychain management
=> feat: Introduce support of simctl features that have been added in Xcode 11.4 SDK

lib/simulator-xcode-11.4.js
https://github.com/appium/appium/issues/14355
=> fix: Switch to AppleSimUtils usage for permission setting

lib/simulator-xcode-9.js
https://github.com/appium/appium/issues/14630
cc @sadafyadegari
=> fix: Add state check before executing 'simctl boot' command

lib/utils.js, package.json
This module fetches too many dependent submodules
=> chore: Remove fkill dependency

lib/simulator-xcode-10.js
https://github.com/appium/appium/issues/14835
=> fix: Properly handle spawn errors on browser startup

lib/geolocation.js
Addresses https://github.com/appium/appium/issues/15613
=> fix: Patch the decimal separator replacement logic

.azure-pipelines.yml, lib/simulator-xcode-9.js, package.json
The previous implementation performed too many extra calls to simctl and was slower
=> chore: Optimize simulator booting process

lib/simulator-xcode-9.js
Addresses https://github.com/appium/appium/issues/16418
=> fix: Disable the autostart of the last opened device by default in preferences

package.json, test/assets/certificate-test-server/server.js
Similar to https://github.com/appium/appium/pull/16539/
=> chore: Switch @dabh/colors to @colors/colors

lib/geolocation.js, lib/utils.js
Addresses https://github.com/appium/appium/issues/17031
=> fix: Update the path to the system macOS Python interpreter

lib/simulator-xcode-14.js, lib/simulator.js, package.json
Based on https://github.com/appium/node-simctl/pull/160
=> feat: Use native location setter for Xcode 14+

lib/geolocation.js, lib/utils.js
Addresses https://github.com/appium/appium/issues/17031#issuecomment-1219283816
=> fix: Replace Python usage with AppleScript calls

lib/simulator-xcode-6.js, test/unit/settings-specs.js
This PR removes launchAndQuit from setReduceMotion
see https://github.com/appium/appium-ios-simulator/pull/342#discussion_r1044429539
=> refactor: do not launch in setReduceMotion

lib/settings.js, lib/simulator-xcode-6.js, test/functional/simulator-e2e-specs.js
=> refactor: Streamline settings helpers for the simulator
