lib/simulator-xcode-6.js
There was a race condition between getting the sim log directory (which is a symlink) and making it. We end up not having any logs.
Use the full path to the sim log directory.
=> Don't use symlink for log location

lib/simulator-xcode-6.js
Add methods needed by Safari lifecycle.
=> Add methods to delete and clean safari

lib/simulator-xcode-6.js, package.json
Was investigating why my Simulator gets corrupted, found that there was still some service running at the time of the xcrun, with the udid in it, so added code to make sure those are stopped.
ping @imurchie @jlipps
=> Better sim shutdown

lib/simulator-xcode-6.js
I trying to use appium@v1.5.0-beta6 with Safari, but it raises the error:
```
error: [MJSONWP] Encountered internal error running command: TypeError: _appiumSupport.util.hasAccess is not a function
at SimulatorXcode7.callee$2$0$ (lib/simulator-xcode-6.js:180:70)
at tryCatch (/Volumes/Second/repos/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Second/repos/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/Second/repos/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at invoke (/Volumes/Second/repos/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at enqueueResult …
```
=> Fix hasAccess usage

.travis.yml, index.js, lib/simulator-xcode-6.js, lib/simulator-xcode-7.js, lib/simulator.js, package.json, test/unit/simulator-specs.js, test/unit/utils-specs.js
Rather than the iOS driver going through the rigamarole of getting the device name for a particular xcode/simulator combination, let this package do it.
=> Add methods for getting device name string

lib/simulator-xcode-6.js
@imurchie would this break anything you know of?
Prior to this change, the sim process would get "shutdown" but the Ui would remain up and be frozen. When in this state, the simulator can't be opened anymore.
=> killAllSimulators when calling sim.shutdown()

README.md, index.js, lib/simulator-xcode-6.js, lib/simulator.js, lib/utils.js, test/unit/simulator-specs.js, test/unit/utils-specs.js
breaking change. Before, we would just create a Simulator object with a completely made up udid, if thats what you asked for.
I don't think that's useful though. When will we be creating simulator objects that aren't tied to actual simulators.
You can still create a fake one if calling the constructor directly. But the `getSimulator` method now checks that the sim exists. Makes sense to me. @imurchie ?
=> BREAKING CHANGE: add simExists() function; getSimulator(udid) throws an error if udid does not exist

README.md, lib/simulator-xcode-6.js, lib/simulator-xcode-7.js, lib/tail-until.js, package.json, test/simulator-e2e-specs.js
This way is less hacky, and removes a dependency from the project.
I also improved the openUrl() function so that it respects async better. It used to return as soon as it was called, now it waits a little bit. (I try to tail the system logs, but unfortunately still have a hardcoded wait :( on top of that)
@imurchie for review
=> Use "openUrl" to start safari in launchAndQuit() instead of using Instruments

lib/settings.js, lib/simulator-xcode-6.js
- Resolves issue where iOS 8 and iOS 8.1 get stuck in a loop waiting for a fresh simulator.
- Takes advantage of a laxer parsePlistFile method, returning a blank plist file instead of throwing.
@jlipps
=> freshSim fix + plist tweak

lib/simulator-xcode-6.js
Please review @imurchie 
Async issue resolved:
We could eventually collapse these logs into one or two lines. To do this we could use a global logging variable or pass through an additional parameter - but this would get messy with 3 libs involved.
Maybe something like:
```
log.debug('Updated Safari plist');
env.logging = 'none'
// process our plists
env.logging = 'info'
log.debug('Updated Safari plist');
```
Is something like this already in place?
=> fixed bundle path map async issue

lib/simulator-xcode-6.js
I got sick of waiting for the test to wait 60 seconds in order to timeout. Investigated and the indicator is the same.
@Jonahss review?
=> Add 9.2 boot indicator

lib/simulator-xcode-6.js, lib/simulator-xcode-7.3.js
We don't need to have the logs folder present to consider the file not fresh.
=> Remove logs from isFresh check

lib/extensions/isolate-sim.js, lib/settings.js, lib/simulator-xcode-6.js, lib/utils.js, package.json, test/unit/simulator-common-specs.js
Updating the locale is a slow process (requiring restart of the device, for instance). So only do it if there are actually changes.
Also, update `lodash`.
=> Make sure locale is not updated if it is not necessary

lib/settings.js, lib/simulator-xcode-6.js, package.json
Remove log lines that get repeated. Calling code ought to log information that is more informative.
=> Clean up logging

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, package.json, test/simulator-e2e-specs.js
There is no reliable boot message in the logs, so rely on the simctl status, which is not as reliable but better than waiting 60s to timeout.
=> Handle boot waiting for iOS 10

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js
The latest Beta has a marker that seems to always come up.
Without this we get errors, especially in Travis, when the sim is "Booted" but not ready to be used.
=> Add iOS 10 boot indicator

lib/settings.js
I assume "Libary" was incorrect.
=> Fix typo in effective settings plist path

lib/simulator-xcode-7.js
part of appium/appium#7122
cc @imurchie
=> map bare 'iPad Simulator' to 'iPad Retina' in ios 10

lib/utils.js, test/unit/utils-specs.js
- If the user provides an invalid UDID, throw a descriptive expression
- Checks if openssl is available. If openssl is not on path, throw an error message telling users that it is required
- InstallSSLCert returns instance of Certificate object now for testing purposes
- Add tests to installSSLCert and uninstallSSLCert
- Installs cert locally, checks that it's there, uninstalls it, checks that it's gone
- Checks that exceptions are thrown correctly
=> Log errors if invalid UDID or openssl not on path

lib/utils.js, test/unit/utils-specs.js
Use `appium-support` `fs.which` function, and make sure the test is catching the correct failure.
=> Make sure uninstall ssl cert test works

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/tail-until.js
Make the startup timeout dynamic, so that iOS 10+ sims can have a longer one. Why oh why is the simulator boot so slow?
This seems to fix, locally at least, the XCUITest issue in which `xcodebuild` errors out with `"Early unexpected exit, operation never finished bootstrapping - no restart will be attempted"`. This seems to happen when the device is not quite ready to get installed to.
=> Use different startup timeout for iOS 10+

lib/certificate.js, test/unit/certificate-specs.js
If there is no keychains folder at the TrustStore library, create one and create a new sqlite db with a tsettings table
**Reviewers: @jlipps @imurchie**
=> TrustStore creates keychains folder if none exists

lib/certificate.js, test/unit/certificate-specs.js
The `sqlite3` module seems to have problems that are hard to pin down, finding the native library it uses (see, for instance, https://github.com/appium/appium/issues/7624). Rather than globally load the module, wait until it is needed, so that the only people affected are the people that need it, and it effort can be made to fix it for them, rather than for lots of people for whom the whole thing is irrelevant.
=> Lazy load the sqlite3 module

lib/simulator-xcode-6.js, test/simulator-e2e-specs.js
Make sure that if we want to, we do not delete the app when cleaning a custom app. This will allow us to do a "fast reset" easily.
See https://github.com/appium/appium/issues/7754
=> Fix cleanCustomApp to be able to retain app

lib/certificate.js, lib/simulator-xcode-6.js, lib/utils.js, package.json, test/assets/certificate-test-server/server.js, test/simulator-e2e-specs.js, test/unit/certificate-specs.js
-Uses teen_process exec to run sqlite3 from command line (sqlite3 comes packaged with OSX)
-Inserts sha1 and data in the hex format because they're both BLOBs
-Added a 'hasRecords' and 'getRecordCount' function that checks how many records are in tsettings and then parses the result
-Checks that 'sqlite3' is available on path before installing an SSL cert (just in case it was uninstalled or unavailable in a future release)
-Updated tests to use new code
Reviewers @jlipps @imurchie
=> Removed sqlite3 dependency

lib/simulator-xcode-8.js
Use process detection instead of looking for magic string in logs. This should make the detection more stable and shorten simulator startup duration.
=> Optimize the way we detect Simulator is booted

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js
IOS simulator allows to execute some xcrun terminal commands even if UI initialisation has not been 100% completed. This will allow us to shorten session init duration if we install/uninstall app under test in parallel while Simulator is still booting.
=> Make it possible to add onBootCompleted callback to Simulator

lib/utils.js, test/unit/utils-specs.js
On 10.12 the killing of sims is often flakey. sending the killall command is much more reliable.
=> Add killall signal in Sierra

lib/simulator-xcode-6.js, test/simulator-e2e-specs.js
I suppose there is no need to start and stop Simulator if there is no directory for the given app. Returning **undefined** means the app has no data to cleanup, which is OK for us. And starting the simulator and then quitting it is a very time-expensive operation.
=> Do not try to start the simulator if there are no folders

lib/logger.js, package.json
Stop using the deprecated `appium-logger`.
=> Move to logger from appium-support

lib/simulator-xcode-6.js, lib/touch-enroll.js, lib/utils.js, test/functional/touch-enroll-e2e-specs.js, test/simulator-e2e-specs.js, test/unit/touch-enroll-specs.js, test/unit/utils-specs.js
* Wrote bindTouchIDKey() method which adds keyboard shortcut to Touch ID Enrollment menu items
* binds key on startup, unbinds key when it's killed
* Wrote enrollTouchID() method that calls Applescript to toggle the above keyboard shortcut
* Wrote unit test that checks that the call is not rejected (can't test the functionality in Simulator, those tests will be in XCUITest Driver)
=> Added enrollTouchID() method to Simulator

lib/simulator-xcode-6.js, lib/touch-enroll.js, test/simulator-e2e-specs.js
* Added 'allowTouchEnroll' as a param to `run` function
* If true, setTouchEnrollKeys is called
* Is not called if `allowTouchEnroll` is false
* Added test to check that enrollKeys are only backed up when `allowTouchEnroll === true`
=> Allow touchEnroll only if variable set to true

lib/simulator-xcode-6.js
AppleScript-based method to hit the "Increase Database" alert that comes up in Safari when a page requests logs of WebSQL/LocalStorage space. This button is not automatable through UI Automation or XCTest.
=> Add method for dismissing possible Increase Database alert

lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, package.json
We need to get rid of all the stuff, which does not work with simctl and the device udid directly (like grepping process names, killing all services by their names, and not by udid, etc), otherwise it will not be possible to isolate simulator interaction in scope of a single session and not to touch all the others parallel sessions running at the same time. We need also to think about adding headless simulator testing support.
=> Make the code more compatible to multiple Simulators management

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js
Some adjustments are still needed to be done on xcuitest driver side, but this patch is not going to break anything anyway. It would be nice to have Xcode9-beta support on Travis, so we can create a functional test for the patch.
=> Add headless capability support to Xcode 9 Simulator

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js
This PR solves Simulator startup issue under Xcode9 in case if the UI client is already running (which is not the case for Xcode8 and earlier because shutdown call kills UI client there and we cannot do it under Xcode9, because it will kill all other booted Simulator instances).
=> Fix Simulator startup if UI client is running under Xcode9

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js
Made the code more readable and easier to debug from logs
=> Add more logging to methods responsible for simulator startup and split logic between Xcode9 and earlier versions

lib/touch-enroll.js
Tune touch enroll tests to avoid the situation when parallel simulators unexpectedly change states of shared user defaults. This will, probably, will require some more work to prevent UI Apple scripts to be executed at the same time.
=> Tune enroll backups logic not to break parallel tests

lib/simulator-xcode-9.js
It looks like newer releases of Simulator UI client may ignore some arguments to start the particular client. That is why we try boot the correct server in any case independently of the UI state.
=> Ensure the correct simulator is booted while UI client is running

.travis.yml
Since Xcode 9 will signal the end of our support for iOS 7.3, there is no need to test that device with that xcode.
I also removed the redundant `os` specification, which is why the diff is so messed up.
=> Stop testing ios 7.3 with xcode 9

lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, package.json
It looks like the current approach is not very stable in parallel tests (it always tries to start the UI client even if it is already running).
=> Improve UI client state detection

lib/simulator-xcode-8.js, lib/simulator-xcode-9.js
It looks like stopping of Simulator services prevents simulator to be properly erased on Xcode9+.
=> Avoid stopping simulator services before erase

lib/simulator-xcode-9.js
The new _verifyDevicePreferences_ method ensures we don't write an invalid value into simulator plist file
=> Add device preferences verification

lib/simulator-xcode-9.js, test/unit/utils-specs.js
After this PR is merged it will only be necessary to add and document the corresponding capability for xcui driver
FYI @vrunoa
=> Apply validation rules for device preferences

lib/simulator-xcode-6.js
The next step will be to include the cleanup of `com.apple.mobile.installd.staging` cache folder into xcuitest driver lgorithm. See https://github.com/appium/appium/issues/9410 for more details.
=> Add a possibility to clear Simulator caches

lib/simulator-xcode-6.js
There is no reason to create a structure with all the info in it by iterating over all the devices, and then searching inside it (by iterating over the structure). 
We are already iterating over all the devices!
=> Clean up stat function

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, lib/utils.js, test/functional/helpers.js, test/functional/simulator-e2e-specs.js, test/functional/utils-e2e-specs.js, test/unit/utils-specs.js
I observe that some functional tests on travis are failing because not all simulators are killed after this method is called. Lets try to fix this.
=> Update killAllSimulators helper

lib/simulator-xcode-8.js
terminate safari only on booted simulators
this fix removes error 
[simctl] Error: simctl error running 'terminate': 
from log when we try to call 'terminate' on non-booted simulator.
See log example in https://github.com/appium/appium/issues/9954#issuecomment-360337526
=> fix: call 'terminate safari' only for booted simulators

index.js, lib/certificate.js, lib/utils.js, test/unit/certificate-specs.js
* Exposed 'hasSSLCert' to API which checks new pemText to check if it already exists as an entry in the Trust Store
* Updated the certificate.has method to check fingerprint too
* If the subj is there but fingerprint is different, then it returns false
* If subj and sha1 are unchanged, then it returns true
* This is so that we can check if a cert is already installed, and if it is, we don't have to restart simulator
=> Add 'hasSSLCert' to API

lib/simulator-xcode-6.js, lib/simulator-xcode-9.3.js, lib/simulator-xcode-9.js, lib/simulator.js, test/functional/simulator-e2e-specs.js
In the first step of providing support for iOS 11.3 web, we need to find the unix domain socket for the simulator.
I've searched _ever_ file on my machine while a sim is running, and can find no reference to the correct socket. The best solution I've come up with is ot use `lsof` and hope that the grouping together of entires for each sim (this works in my experimentation).
=> Add method to get ios 9.3 web inspector socket

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, test/functional/simulator-e2e-specs.js
* Went in to fix IOS Simulator because tests were failing for touchId on iPhone X (because iPhone X doesn't support touchId)
* Went ahead and added `faceId` as a biometric that can also be used alongside `touchId` since it's something that has been asked for and probably will be in high demand
* Updated tests to test both and also updated tests to catch exceptions
* Will update `appium-xcuitest-driver` next to use the new interface
=> Add faceId biometrics

lib/simulator-xcode-9.js
We've finally got a response from Apple and they suggested to enable Hardware->Rotate Device Automatically Simulator option in order for its window to follow the actual screen orientation set on XCUIDevice instance.
=> Set simulator window to be rotated automatically when asked

.travis.yml
Adjust the config to support Xcode 9.4. Right now we cannot run iOS < 11.4 on Xcode 9.4 because those VMs do not have the SDKs installed. They are aware of this fact.
=> Update Travis config to use Xcode 9.4

lib/simulator-xcode-9.js, test/unit/simulator-xcode-9-specs.js
I encountered below error when I called touch id enrollment feature.
> @driver.toggle_touch_id_enrollment true
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: [object Object] is not a valid biometric. Use one of: ["touchId","faceId"]
from UnknownError: An unknown server-side error occurred while processing the command. Original error: [object Object] is not a valid biometric. Use one of: ["touchId","faceId"]
- `biometricName` is `{menuName: "Touch id"}`
- `BIOMETRICS` is `{touchId: {menuName: "Touch id"}, faceId: {menuName: "Face id"}}`
- Hence, `BIOMETRICS[biometricName]` never be true
~~This PR fix the behaviour to make sure the `menuName` exists in `BIOMETRICS`.~~
Use 'touchId' instead of …
=> fix getting biometric

lib/simulator-xcode-8.js
It looks like Apple is getting super paranoid about security in Mojave-beta. This patch allows to avoid errors in UI state detection
=> Fall back to non-AppleScript UI state detection if necessary permissions are missing

lib/calendar.js, lib/simulator-xcode-10.js, lib/simulator-xcode-8.js, lib/simulator.js
Xcode 10b5 introduced another field to the access database, as well as the situation where the app container has a value, but it does not exist yet.
=> Update for Xcode 10b5

lib/settings.js, package.json
This is the only place in our dependency tree where [semver-compare](https://www.npmjs.com/package/semver-compare) is used:
```
$ npm ls semver-compare
appium@1.8.0-beta /Users/isaacmurchie/code/appium
└─┬ appium-ios-driver@2.8.0
└─┬ appium-ios-simulator@3.2.0
└── semver-compare@1.0.0
```
The functionality is easily duplicated using [semver](https://www.npmjs.com/package/semver), which is used all over:
```
$ npm ls semver                                                                                                                                                                                                            8.10.0
appium@1.8.0-beta /Users/isaacmurchie/code/appium
├─┬ appium-android-driver@3.4.0
│ ├─┬ appium-adb@6.15.2
│ │ └── semver@5.5.0  deduped
│ └─┬ …
```
=> Move semver-compare to semver.lt

lib/settings.js, lib/simulator-xcode-6.js, test/unit/settings-specs.js
We have all the machinery in place to check if requested settings values are different from current values. This can be important since changed values means rebooting a simulator. Calling code will have to be updated to take the return value and either reboot or not, depending on need.
=> Only update settings if necessary

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js
Mac OS Mojave blocks Apple script execution without special permissions, so we must have a fallback there.
=> Tune isUIClientRunning verification

lib/logger.js, lib/simulator-xcode-6.js, lib/simulator.js, lib/utils.js, package.json, test/unit/calendar-specs.js, test/unit/certificate-specs.js, test/unit/isolate-sim-specs.js, test/unit/simulator-common-specs.js
Updating logging so the prefix is changed depending on the platform. This will not work if there are multiple simulators of different platforms (since the logger is shared) but that bridge can be crossed if/when it is reached.
Logs become like:
```
info tvOSSim Constructing tvOS simulator for Xcode version 9.4.1 with udid 'C2DEBF4F-D7D4-4A3F-8A31-13E86B505B1B'
info iOSSim Constructing iOS simulator for Xcode version 9.4.1 with udid '697D0C48-A7E6-4BBC-9112-015BE58D9432'
info watchOSSim Constructing watchOS simulator for Xcode version 9.4.1 with udid '861897A6-9E93-4423-9D5E-8D9FCDD84611'
```
=> Add ability to change log prefix depending on platform

lib/simulator-xcode-8.js
Number formatting depends on System preferences and Locale.
Issues occurs if user is using commas as decimal separator.
As string formatting should fix this problem.
=> Fix geolocation coordinates format

.travis.yml, lib/permissions.js, lib/simulator-xcode-11.js, lib/simulator-xcode-6.js, lib/simulator.js, test/functional/simulator-e2e-specs.js
This started as just a simple addition of Xcode 11 into the build, but that failed. So...
1. Override `getLaunchDaemonsRoot` for Xcode 11 since the directory structure has changed from `[...]/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/[...]` to `[...]/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/[...]`. _Thanks Apple._
1. Run permissions tests in Travis, since they did not work anywhere. This involved installing the Wix tooling, and adding a function to set a single permission (which seemed to be the idea behind what was written in the test). I also inverted the arguments to some functions so they are all the same.
=> fix: get tests to run on xcode 11 in Travis

lib/settings.js, lib/simulator-xcode-6.js, test/functional/simulator-e2e-specs.js
https://github.com/appium/appium-xcuitest-driver/pull/1052#discussion_r319355030
In like below path has user installed `.app`. This method read Info.plist in the `.app` and returns a list of bundle ids which has provide bundle name.
```
/Users/kazu/Library/Developer/CoreSimulator/Devices/E9245A58-B499-4B76-8FB1-7FA1342F3085/data/Containers/Bundle/Application/210A3413-B313-443A-A5EC-CB6CF1C5E84F/
```
=> feat: get user installed bundleids by bundlename

lib/simulator-xcode-6.js
If there are no bundle identifiers the current log line looks quite odd.
=> fix: clean up logging of bundle ids for bundle name

lib/geolocation.js, lib/simulator-xcode-8.js
https://github.com/lyft/set-simulator-location
This works on Xcode 11.2 environment on my env. (against iOS 12 and iOS 13)
Current idb does not work well on Xcode 11 env, so, let's try another way before idb try.
- ok
```
[HTTP] --> POST /wd/hub/session/857ac20d-beac-4409-ac0a-75a37aa833c9/location
[HTTP] {"location":{"latitude":34.18583,"longitude":131.47139,"altitude":0}}
[debug] [W3C (857ac20d)] Calling AppiumDriver.setGeoLocation() with args: [{"latitude":34.18583,"longitude":131.47139,"altitude":0},"857ac20d-beac-4409-ac0a-75a37aa833c9"]
[debug] [XCUITest] Executing command 'setGeoLocation'
[debug] [W3C (857ac20d)] Responding to client with driver.setGeoLocation() result: null
[HTTP] <-- POST /wd/hub/session/857ac20d-beac-4409-ac0a-75a37aa833c9/location 200 279 ms - 14
[HTTP]
```
- …
=> feat: Add setting geolocation by set-simulator-location as the first method

lib/simulator.js
There are times when we know, when calling `getSimulator`, that the simulator exists (for instance, when we have just created it). On my machine, using iOS 13+, it takes around 10 seconds to check for the existence of the simulator, so skipping it is not a trivial thing.
=> feat: allow passing in of platform

lib/simulator-xcode-6.js
Reference: 
- https://github.com/WebKit/webkit/blob/master/Tools/Scripts/webkitpy/xcode/simulated_device.py#L413
- https://twitter.com/steipete/status/1227551552317140992?s=20
This argument improves launching simulator performance.
Once this pasteboard sync disabled, the pasteboard cannot sync with macOS system with simulators. In a case a user would like to sync such pasteboard, I'd like to add `disablePasteboardAutomaticSync` as caps.
https://github.com/appium/appium-ios-driver/blob/master/lib/desired-caps.js
Then, `PasteboardAutomaticSync` follows the global preference.
```
defaults read com.apple.iphonesimulator PasteboardAutomaticSync
```
On my machine, this disableness improved the launching performance around two seconds.
=> feat: disable pasteboard sync in launching time to improve the performance

lib/geolocation.js, lib/simulator-xcode-11.4.js, lib/simulator-xcode-8.js
The iOS simulator menu bar now (as of Xcode 11.4) has a "Features" menu, and the "Location" menu item has been moved into it. So add the ability to specify what the menu is in order to make AppleScript geolocation setting work again.
Up to Xcode 11.4:
Xcode 11.4:
With this the entire "basic" test suite from `appium-xcuitest-driver` successfully runs with Xcode 11.4 beta 3.
=> fix: allow Xcode 11.4 geolocation setting through AppleScript

lib/simulator-xcode-11.4.js
In the previous implementation the order of checks was incorrect, so, for example, the 'medialibrary' permission was always recognised as non-native instead of being transformed to `media-library`
=> fix: Fix handling of the native media library permission

lib/simulator-xcode-6.js, lib/simulator-xcode-8.js, lib/simulator-xcode-9.js, lib/utils.js
I've checked how `focus` command is implemented in idb code and ported it to PyObjC
=> refactor: Prefer own implementation of app activation over idb one

lib/simulator-xcode-11.4.js, lib/simulator-xcode-9.js
Simulators remain minimized when running tests with Xcode 11.4.1. Fix was to launch simulator UI client before simulators are booted.
=> fix: sim window minized on xcode 11.4

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, package.json, test/functional/simulator-e2e-specs.js
The `stat` method internally invokes `simctl list`, which could be pretty slow, especially if multiple simulators are installed on the system. I've switched the state detection API to use `getenv` call as a workaround. In opposite to the `list` call it only queries single simulator, which makes the overall performance better. On my machine the timings were:
```
$ time xcrun simctl getenv 0B2C9CE6-29AC-4494-B64F-CE711619146E dummy
...
xcrun simctl getenv 0B2C9CE6-29AC-4494-B64F-CE711619146E dummy  0.08s user 0.09s system 88% cpu 0.184 total
```
```
$ % time xcrun simctl list
....
xcrun simctl list  0.11s user 0.20s system 43% cpu 0.723 total
```
=> refactor: Change simulator state detection logic to use faster APIs

.travis.yml, lib/simulator-xcode-11.4.js, lib/simulator.js, test/unit/simulator-specs.js
Makes a call to `xcrun simctl privacy...` instead of directly editing TCC.db to grant calendar access.
Also changes the simulator.js logic so 
1. it explicitly throws an error if Xcode versions 1 ~> 5 are provided.
2. if anything >= 11.4 is provided, it will default to `simulator-xcode-11.4` implementation
_WHY?_ So that when Xcode 13 comes out it will, by default, use the latest Xcode implementation. And if it works (ie: our e2e tests keep passing) we don't need to do anything
(depends on https://github.com/appium/node-simctl/pull/114 ... make sure to publish this first and bump up min node-simctl before merging)
=> fix: use simctl privacy for calendar access

lib/geolocation.js
Simulator UI does not accept values if a wrong decimal separator is used.
cc @wswebcreation
=> fix: Use system-wide decimal separator in the location script

.azure-pipelines.yml, azure-templates/base_unit_test_job.yml, lib/defaults-utils.js, lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, lib/utils.js, package.json, test/unit/defaults-utils-specs.js
Plist preference files on macOS are managed by cfprefsd. Changing the file itself without letting the daemon know about it has no effect. Read https://eclecticlight.co/2017/07/06/sticky-preferences-why-trashing-or-editing-them-may-not-change-anything/ and https://shadowfile.inode.link/blog/2018/06/advanced-defaults1-usage/ for more details
=> fix: Update simulator preferences handling

lib/simulator-xcode-9.js, test/unit/certificate-specs.js
On some platforms due to a race condition the bootSimulator API could be called more than once, which invokes an unexpected UI alert ("Cannot ... in the current state: Booted"). These changes ensure the boot API is only called once.
=> fix: Update Simulator booting validation

lib/geolocation.js
This fixes two issues with `setGeoLocation`:
1. The `idb` location setter is throwing an error even on success, making the fallback `AppleScript` location setter always run
1. The `AppleScript` location setter fails to set valid coordinates for certain locales due to a wrong calculation of the decimal separator
To test:
1. On macOS go to `Language and Region` → `System Preferences` and either change your locale settings or change the separator by going to `Advanced` → `Number separators` → `Decimal`
1. Run the script to see your changes reflected:
```shell
osascript -e 'use framework "Foundation"' -e 'return (decimalSeparator of init() of alloc() of NSNumberFormatter of current application as string)'
```
1. Open Simulator,  enter Custom Location /w the new separator: `Feature` → …
=> fix: idb and AppleScript Geo Location setters

lib/defaults-utils.js, lib/simulator-xcode-9.js, test/functional/simulator-e2e-specs.js, test/unit/defaults-utils-specs.js
The idea is similar to https://github.com/appium/appium-ios-simulator/pull/298 except of Simulator has its own `defaults` tool, which could be triggered via `simctl spawn`
=> feat: Add a possibility to change locale settings without restarting the Simulator

lib/simulator-xcode-9.js
I figured out how to apply https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBConfiguration.m#L268 for iOS 15 simulators.
We can modify the preference only via its domain. The WDA one is for iOS 14-.
No issues happen by calling this for lower than iOS 15 simulators.
After this change, `com.apple.keyboard.preferences` will hale the below on simulator iOS 15:
```
% xcrun simctl spawn booted defaults read com.apple.keyboard.preferences
{
DictationLanguagesEnabled =     {
"en_US" = 1;
};
DidShowContinuousPathIntroduction = 1;
}
```
=> feat: add DidShowContinuousPathIntroduction 1 for iOS 15

lib/settings.js, lib/simulator-xcode-6.js, test/functional/simulator-e2e-specs.js, test/unit/settings-specs.js
This PR adds setReduceTransparency function that allows to switch `Reduce Transparency` in accessibility preference.
Please see  https://github.com/appium/appium/issues/17905 for the background, and feel free to close this if this feature request doesn't make sense.
I found `ReduceMotion` is implemented with a different approach https://github.com/appium/WebDriverAgent/pull/202
I'm not sure which way is better though, I confirmed `EnhancedBackgroundContrastEnabled` can be changed in runtime and reflected immediately. So I chose this way but please let me know if WDA is better then I'll try to do it.
=> feat: add setReduceTransparency

lib/simulator-xcode-6.js, lib/simulator-xcode-9.js, test/functional/simulator-e2e-specs.js
There is no need to restart Simulator in order to apply its preferences (and it does not work as well).
The right way of doing that now is by invoking `defaults` CLI. It also notifies cfprefsd, so various apps and services could pick up settings change in runtime. 
cc @rerorero
=> fix: Update Simulator preferences configuration

lib/extensions/permissions.js
Found an issue in ruby's func test code:
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=24363&view=logs&j=9ea0b8ba-2eaf-5ebd-f027-f9e150263999&t=2cce7409-2ec4-50f8-2653-6fd0ce207c6c
```
Minitest::UnexpectedError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'udid')
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'udid')
```
---
The below one will be in https://github.com/appium/appium-ios-simulator/pull/351
I also wonder if the getAcccess might need to use https://github.com/wix/AppleSimulatorUtils as …
=> fix: udid reference in setAccess

lib/simulator-xcode-9.3.js, test/unit/simulator-specs.js
We have assumed that we always obtain `lsof -aUc launchd_sim` result in a specific order. (e.g. an output line like `/com.apple.CoreSimulator.SimDevice.D7082A5C-34B5-475C-994E-A21534423B9E` always comes before `com.apple.webinspectord_sim.socket` line) However, sometimes the assumption seems to be wrong (as far as I checked it can happen since Xcode 13.4.1. I haven't seen this phenomenon on Xcode 13.1 or earlier). Therefore, it is most likely necessary to obtain an appropriate unix socket path without depending on the order of the output.
=> fix: retrieve an appropriate unix socket path

README.md, lib/extensions/geolocation.js
https://github.com/MobileNativeFoundation/set-simulator-location is now under Mobile Native Foundation from Lyft
=> chore: update links for set-simulator-location

lib/extensions/permissions.js
This PR is to fix getAcccess for iOS 14+ after https://github.com/appium/appium-ios-simulator/pull/350
https://github.com/wix/AppleSimulatorUtils/blob/5467857407da4653305af119b2486051664a4f97/applesimutils/applesimutils/SetServicePermission.m
Should handle iOS version, or probably try iOs 14's first then fallback to existing one if an exception occurs only
=> fix: add ios 14 and above case

.github/workflows/functional-test.yml, lib/simulator-xcode-15.js, lib/simulator.js
The simruntime has been moved to a mountable image now.
Also I've noticed that the hidden `simctl appinfo` command dos not resolve system apps now
=> feat: Add Xcode15 support

lib/simulator-xcode-15.js
According to https://github.com/appium/appium/issues/18749#issuecomment-1644903756 , probably `await this.simctl.getEnv('IPHONE_SIMULATOR_ROOT')` included a new line. Then, the built path could have `\n`.
It might be safe to do `trim()`
=> fix: isAppInstalled in lib/simulator-xcode-15.js

lib/extensions/settings.js, test/functional/simulator-e2e-specs.js
This PR adds `setAutoFillPasswordsEnabled` function that allows to switch `AutoFill Passwords` preference.
The background is that the default AutoFill password setting has been changed since iOS16, and the behavior has been changed to suggest autofillable passwords when entering passwords. I would like to align the AutoFill Passwords settings for cross version testing. Also here is another request to disable it for another reason https://github.com/SeleniumHQ/selenium/issues/11426
Note that `setAutoFillPasswordsEnabled` enables/disables autofill settings internally but it's not reflected in the appearance of toggle switch on the settings application.
ref: [related discussion ](https://appium.slack.com/archives/C02956V3H/p1692779001358339)
=> feat: Add setAutoFillPasswordsEnabled function

lib/device-utils.js, lib/utils.js, test/unit/simulator-specs.js, test/unit/utils-specs.js
Unfortunately I did not find a possibility in sinon to properly stub an exported ESM class, so some tests have been removed as the result.
Related to https://github.com/appium/appium-ios-simulator/pull/384#issuecomment-1732156120
=> tests: Fix tests after the recent node-simctl update

lib/simulator-xcode-9.js
- address: https://github.com/appium/appium/issues/19181
- I confirmed the behaviour using Xcode 14.3.1 and iOS simulator 16.4.
- As far as I checked locally, we don't need anything for the following system prompts
- Access to Your Photos
- Access to Your Microphone
- Access to Your Contacts
- Request App Store Reviews
- Enable iCloud Syncing
- App Tracking Transparency
=> fix: appropriately translate com.apple.SpringBoard and some system prompts

lib/simulator-xcode-9.js
I assume there is no need to restart springboard if only keyboard or locale changes are applied. 
Relates to https://github.com/appium/appium/issues/19202
cc @mwakizaka
=> fix: Only restart springboard if the system language is changed

lib/simulator-xcode-9.js
- Continued from https://github.com/appium/appium-ios-simulator/pull/384
- When using iOS 16.1 simulator on Xcode 15.0 (CoreSimulator-932.2, xcrun version 67), the following system prompts are not appropriately translated.
1. `"<App name>" Would Like to Access the Camera`
2. `"<App name>" Would Like to Access the Microphone`
3. `"<App name>" Would Like to Access Your Contacts`
4. `"<App name>" Would Like to Access Your Photos`
5. `Allow "<App name>" to track your activity across other companies' apps and websites`
By stopping `com.apple.tccd`, I've confirmed the above system prompts are appropriately translated.
=> fix: appropriately translate some system prompts on iOS 16.1 simulator

lib/extensions/settings.js, test/unit/simulator-specs.js
Hi, 
I happened to find that we need to stop `com.apple.akd` as well for appropriately translating `Sign in with your Apple ID` system prompt.
- Before
- After
=> fix: system prompt for Apple ID sign in unexpectedly not translated

lib/defaults-utils.js
```
lib/defaults-utils.js:15:14 - error TS2304: Cannot find name 'Node'.
15  * @returns {Node|string} Either string or raw node representation of
~~~~
lib/defaults-utils.js:28:7 - error TS18047: 'xmlDoc.documentElement' is possibly 'null'.
28       xmlDoc.documentElement.appendChild(keyEl);
~~~~~~~~~~~~~~~~~~~~~~
lib/defaults-utils.js:31:7 - error TS18047: 'xmlDoc.documentElement' is possibly 'null'.
31       xmlDoc.documentElement.appendChild(subValueEl);
~~~~~~~~~~~~~~~~~~~~~~
lib/defaults-utils.js:38:7 - error TS18047: 'xmlDoc.documentElement' is possibly 'null'.
38       xmlDoc.documentElement.appendChild(subValueEl);
~~~~~~~~~~~~~~~~~~~~~~
lib/defaults-utils.js:49:5 - error TS18047: 'xmlDoc.documentElement' is possibly 'null'.
49     xmlDoc.documentElement.appendChild(valueTextEl); …
```
=> fix: type error by xmldom

lib/extensions/settings.js, lib/simulator-xcode-10.js, lib/simulator-xcode-15.js, lib/types.ts, package.json
adds https://github.com/appium/node-simctl/pull/262
So, far, I made these commands available since Xcode 15 since I haven't confirmed Xcod 14 as no env. We'll be able to bring them to older env if we get a bug report.
=> feat: add increase contrast and content size commands

lib/extensions/permissions.js
Closes https://github.com/appium/appium/issues/21116.
Inherits https://github.com/appium/appium-ios-simulator/pull/445.
=> fix: Wait for springboard restart and spotlight application restart after applesimutils invocation

lib/extensions/safari.js, package.json
BREAKING CHANGE: Required Node.js version has been bumped to ^20.19.0 || ^22.12.0 || >=24.0.0
BREAKING CHANGE: Required npm version has been bumped to >=10
=> feat: Bump Node.js version
